version: '2'
services:
    postgisdb:
        container_name: postgis_dbserver
        image: kartoza/postgis
        volumes:
            - postgisvolume:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=jj
            - POSTGRES_DBNAME=wikipediastreetnamefilter
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 54329:5432

volumes:
    postgisvolume: {}
